-- Create enums for incident tracking
CREATE TYPE "IncidentRecordType" AS ENUM ('MISTAKE', 'WARNING');
CREATE TYPE "IncidentStatus" AS ENUM ('PENDING', 'CONFIRMED', 'REJECTED');
CREATE TYPE "IncidentAppealDecision" AS ENUM ('PENDING', 'APPROVED', 'DECLINED');
CREATE TYPE "IncidentFinalAction" AS ENUM ('NONE', 'HOUR_REDUCTION', 'TERMINATION');
CREATE TYPE "IncidentHistoryType" AS ENUM ('NOTE', 'APPEAL', 'SYSTEM', 'MANAGER_COMMENT');

-- Create main incident record table
CREATE TABLE "IncidentRecord" (
    "id" TEXT NOT NULL,
    "employeeId" TEXT NOT NULL,
    "name" TEXT NOT NULL,
    "department" TEXT NOT NULL,
    "manager" TEXT NOT NULL,
    "recordType" "IncidentRecordType" NOT NULL,
    "occurrenceDate" TIMESTAMP(3) NOT NULL,
    "issuedBy" TEXT NOT NULL,
    "status" "IncidentStatus" NOT NULL DEFAULT 'PENDING',
    "appealDecision" "IncidentAppealDecision" NOT NULL DEFAULT 'PENDING',
    "decisionDate" TIMESTAMP(3),
    "reviewedBy" TEXT,
    "finalAction" "IncidentFinalAction" NOT NULL DEFAULT 'NONE',
    "isAutoGenerated" BOOLEAN NOT NULL DEFAULT false,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" TIMESTAMP(3) NOT NULL,

    CONSTRAINT "IncidentRecord_pkey" PRIMARY KEY ("id")
);

-- Create incident history table
CREATE TABLE "IncidentHistory" (
    "id" TEXT NOT NULL,
    "incidentId" TEXT NOT NULL,
    "memo" TEXT NOT NULL,
    "type" "IncidentHistoryType" NOT NULL,
    "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "createdBy" TEXT NOT NULL,

    CONSTRAINT "IncidentHistory_pkey" PRIMARY KEY ("id")
);

-- Add indexes
CREATE INDEX "IncidentRecord_employeeId_status_recordType_idx" ON "IncidentRecord"("employeeId", "status", "recordType");
CREATE INDEX "IncidentRecord_occurrenceDate_idx" ON "IncidentRecord"("occurrenceDate");
CREATE INDEX "IncidentHistory_incidentId_createdAt_idx" ON "IncidentHistory"("incidentId", "createdAt");

-- Add foreign keys
ALTER TABLE "IncidentRecord" ADD CONSTRAINT "IncidentRecord_employeeId_fkey" FOREIGN KEY ("employeeId") REFERENCES "Employee"("id") ON DELETE CASCADE ON UPDATE CASCADE;
ALTER TABLE "IncidentHistory" ADD CONSTRAINT "IncidentHistory_incidentId_fkey" FOREIGN KEY ("incidentId") REFERENCES "IncidentRecord"("id") ON DELETE CASCADE ON UPDATE CASCADE;
