"use client";

import { useEffect, useMemo, useRef, useState } from "react";
import type { Employee } from "@/lib/employees";
import { formatCompactDate, formatShortDate } from "@/lib/dateUtils";

type RecordType = "MISTAKE" | "WARNING";
type RecordStatus = "PENDING" | "CONFIRMED" | "REJECTED";
type AppealDecision = "PENDING" | "APPROVED" | "DECLINED";
type FinalAction = "NONE" | "HOUR_REDUCTION" | "TERMINATION";

type IncidentRecord = {
  id: string;
  employeeId: string;
  name: string;
  department: string;
  manager: string;
  recordType: RecordType;
  occurrenceDate: string;
  issuedBy: string;
  reason: string;
  status: RecordStatus;
  appealDecision: AppealDecision;
  decisionDate: string;
  reviewedBy: string;
  finalAction: FinalAction;
  isAutoGenerated: boolean;
  meetingCompleted: boolean;
  emailSent: boolean;
  followUpEmailSent: boolean;
  improvementPlanReceived: boolean;
  totals: {
    confirmedMistakes: number;
    confirmedWarnings: number;
    requiresDisciplinaryAction: boolean;
  };
  histories: Array<{
    id: string;
    memo: string;
    type: "NOTE" | "APPEAL" | "SYSTEM" | "MANAGER_COMMENT";
    createdAt: string;
    createdBy: string;
  }>;
};

type IncidentTrackingTableProps = {
  employees: Employee[];
};

export default function IncidentTrackingTable({ employees }: IncidentTrackingTableProps) {
  const [records, setRecords] = useState<IncidentRecord[]>([]);
  const [loading, setLoading] = useState(false);
  const [savingId, setSavingId] = useState<string | null>(null);
  const [message, setMessage] = useState<string>("");

  const [employeeId, setEmployeeId] = useState("");
  const [manager, setManager] = useState("");
  const [recordType, setRecordType] = useState<RecordType>("MISTAKE");
  const [occurrenceDate, setOccurrenceDate] = useState(
    new Date().toISOString().split("T")[0]
  );
  const [issuedBy, setIssuedBy] = useState("");
  const [reason, setReason] = useState("");
  const [historyMemo, setHistoryMemo] = useState("");
  const [editingRecordId, setEditingRecordId] = useState<string | null>(null);
  const [showCreateForm, setShowCreateForm] = useState(false);
  const [selectedEmployeeFilter, setSelectedEmployeeFilter] = useState("");
  const editSectionRef = useRef<HTMLDivElement | null>(null);

  const [reviewDrafts, setReviewDrafts] = useState<
    Record<string, {
      manager: string;
      recordType: RecordType;
      occurrenceDate: string;
      issuedBy: string;
      reason: string;
      status: RecordStatus;
      appealDecision: AppealDecision;
      finalAction: FinalAction;
      meetingCompleted: boolean;
      emailSent: boolean;
      followUpEmailSent: boolean;
      improvementPlanReceived: boolean;
      reviewedBy: string;
      decisionDate: string;
      note: string;
    }>
  >({});

  const [emailDraft, setEmailDraft] = useState<{
    incidentId: string;
    isFollowUp: boolean;
    to: string;
    cc: string;
    bcc: string;
    subject: string;
    body: string;
    attachments: File[];
  } | null>(null);
  const [sendingEmail, setSendingEmail] = useState(false);
  const [autoSavedPendingWarning, setAutoSavedPendingWarning] = useState<Record<string, string>>({});

  const DEFAULT_BCC = "chisu@wuc.edu, yuguo@wuc.edu, yannhuang@wuc.edu";

  const getStatusFromAppealDecision = (decision: AppealDecision): RecordStatus => {
    if (decision === "DECLINED") return "CONFIRMED";
    if (decision === "APPROVED") return "REJECTED";
    return "PENDING";
  };

  const fetchRecords = async () => {
    try {
      setLoading(true);
      const response = await fetch("/api/incidents");
      if (!response.ok) throw new Error("Failed to fetch incident records");
      const data = await response.json();
      const incoming: IncidentRecord[] = data?.records || [];
      setRecords(incoming);

      setReviewDrafts((previous) => {
        const next: typeof previous = { ...previous };
        for (const record of incoming) {
          const latestMemo = record.histories?.[0]?.memo || "";
          if (!next[record.id]) {
            next[record.id] = {
              manager: record.manager,
              recordType: record.recordType,
              occurrenceDate: record.occurrenceDate,
              issuedBy: record.issuedBy,
              reason: record.reason,
              status: getStatusFromAppealDecision(record.appealDecision),
              appealDecision: record.appealDecision,
              finalAction: record.finalAction,
              meetingCompleted: record.meetingCompleted,
              emailSent: record.emailSent,
              followUpEmailSent: record.followUpEmailSent,
              improvementPlanReceived: record.improvementPlanReceived,
              reviewedBy: record.reviewedBy || "",
              decisionDate: record.decisionDate || "",
              note: latestMemo,
            };
          } else if (!next[record.id].note && latestMemo) {
            next[record.id] = {
              ...next[record.id],
              note: latestMemo,
            };
          }
        }
        return next;
      });
    } catch (error) {
      console.error(error);
      setMessage("Failed to load incident records.");
    } finally {
      setLoading(false);
    }
  };

  useEffect(() => {
    fetchRecords();
  }, []);

  const selectedEmployee = useMemo(
    () => employees.find((employee) => employee.id === employeeId),
    [employees, employeeId]
  );

  const sortedEmployees = useMemo(
    () =>
      [...employees].sort((a, b) =>
        a.id.localeCompare(b.id, undefined, {
          numeric: true,
          sensitivity: "base",
        })
      ),
    [employees]
  );

  const positionOptions = useMemo(
    () =>
      [...new Set(employees.map((employee) => employee.position).filter(Boolean))].sort(
        (a, b) => a.localeCompare(b)
      ),
    [employees]
  );

  const handleCreateRecord = async () => {
    if (!employeeId || !manager || !issuedBy || !occurrenceDate || !reason.trim()) {
      setMessage("Please complete employee, manager, issued by, occurrence date, and reason.");
      return;
    }

    try {
      setLoading(true);
      setMessage("");

      const response = await fetch("/api/incidents", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          employeeId,
          manager,
          recordType,
          occurrenceDate,
          issuedBy,
          reason: reason.trim(),
          historyMemo: historyMemo || undefined,
        }),
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data?.details || data?.error || "Failed to create record");
      }

      await fetchRecords();
      setMessage("Incident record saved successfully.");
      setRecordType("MISTAKE");
      setReason("");
      setHistoryMemo("");
    } catch (error) {
      console.error(error);
      setMessage(error instanceof Error ? error.message : "Failed to create record.");
    } finally {
      setLoading(false);
    }
  };

  const handleReviewSave = async (
    recordId: string,
    draftOverride?: {
      manager: string;
      recordType: RecordType;
      occurrenceDate: string;
      issuedBy: string;
      reason: string;
      status: RecordStatus;
      appealDecision: AppealDecision;
      finalAction: FinalAction;
      meetingCompleted: boolean;
      emailSent: boolean;
      followUpEmailSent: boolean;
      improvementPlanReceived: boolean;
      reviewedBy: string;
      decisionDate: string;
      note: string;
    }
  ) => {
    const draft = draftOverride ?? reviewDrafts[recordId];
    if (!draft) return;

    try {
      setSavingId(recordId);
      setMessage("");

      const response = await fetch(`/api/incidents/${recordId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          manager: draft.manager,
          recordType: draft.recordType,
          occurrenceDate: draft.occurrenceDate,
          issuedBy: draft.issuedBy,
          reason: draft.reason,
          appealDecision: draft.appealDecision,
          finalAction: draft.finalAction,
          meetingCompleted: draft.meetingCompleted,
          emailSent: draft.emailSent,
          followUpEmailSent: draft.followUpEmailSent,
          improvementPlanReceived: draft.improvementPlanReceived,
          reviewedBy: draft.reviewedBy || null,
          decisionDate: draft.decisionDate || null,
          historyMemo: draft.note || undefined,
          historyType: "MANAGER_COMMENT",
          historyCreatedBy: draft.reviewedBy || "MANAGER",
        }),
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data?.details || data?.error || "Failed to update record");
      }

      await fetchRecords();
      setReviewDrafts((previous) => ({
        ...previous,
        [recordId]: {
          ...previous[recordId],
          status: getStatusFromAppealDecision(previous[recordId].appealDecision),
        },
      }));
      setMessage("Record review updated.");
      setEditingRecordId(null);
    } catch (error) {
      console.error(error);
      setMessage(error instanceof Error ? error.message : "Failed to update record.");
    } finally {
      setSavingId(null);
    }
  };

  const handleDeleteRecord = async (recordId: string) => {
    const confirmed = window.confirm("Are you sure you want to delete this incident record?");
    if (!confirmed) return;

    try {
      setSavingId(recordId);
      setMessage("");

      const response = await fetch(`/api/incidents/${recordId}`, {
        method: "DELETE",
      });

      const data = await response.json();
      if (!response.ok) {
        throw new Error(data?.details || data?.error || "Failed to delete record");
      }

      await fetchRecords();
      setMessage("Incident record deleted.");
    } catch (error) {
      console.error(error);
      setMessage(error instanceof Error ? error.message : "Failed to delete record.");
    } finally {
      setSavingId(null);
    }
  };

  const handlePrintIncidentReport = () => {
    const printWindow = window.open("", "_blank", "width=1400,height=900");
    if (!printWindow) {
      setMessage("Unable to open print window. Please allow popups and try again.");
      return;
    }

    const rowsHtml = filteredRecords
      .map(
        (record) => `
          <tr>
            <td>${record.name} (${record.employeeId})</td>
            <td>${record.department}</td>
            <td>${record.manager}</td>
            <td>${record.recordType}</td>
            <td>${record.occurrenceDate}</td>
            <td>${record.issuedBy}</td>
            <td>${record.reason}</td>
            <td>${record.appealDecision}</td>
            <td>${record.decisionDate || ""}</td>
            <td>${getStatusFromAppealDecision(record.appealDecision)}</td>
          </tr>
        `
      )
      .join("");

    printWindow.document.write(`
      <html>
        <head>
          <title>Incident Records and Totals</title>
          <style>
            @page { size: landscape; margin: 14mm; }
            body { font-family: Arial, sans-serif; color: #111827; }
            h1 { font-size: 20px; margin: 0 0 6px; }
            p { font-size: 12px; margin: 0 0 12px; color: #4b5563; }
            table { width: 100%; border-collapse: collapse; font-size: 12px; }
            th, td { border: 1px solid #d1d5db; padding: 8px; text-align: left; vertical-align: top; }
            th { background: #f3f4f6; }
            td:nth-child(7) { max-width: 260px; white-space: pre-wrap; word-break: break-word; }
          </style>
        </head>
        <body>
          <h1>Incident Records and Totals</h1>
          <p>Generated on ${new Date().toLocaleString()}</p>
          <table>
            <thead>
              <tr>
                <th>Employee</th>
                <th>Department</th>
                <th>Manager</th>
                <th>Record Type</th>
                <th>Occurrence Date</th>
                <th>Issued By</th>
                <th>Reason</th>
                <th>Appeal Decision</th>
                <th>Decision Date</th>
                <th>Status</th>
              </tr>
            </thead>
            <tbody>
              ${rowsHtml || '<tr><td colspan="9">No records available</td></tr>'}
            </tbody>
          </table>
        </body>
      </html>
    `);

    printWindow.document.close();
    printWindow.focus();
    printWindow.print();
  };

  const handleEmailIncidentReport = async (record: IncidentRecord) => {
    const employee = sortedEmployees.find((entry) => entry.id === record.employeeId);
    if (!employee?.email) {
      setMessage(`Unable to email: employee email for ${record.name} was not found.`);
      return;
    }

    const managerName = (record.manager || "").trim().toLowerCase();
    const managerEmployee = sortedEmployees.find(
      (employee) => employee.name.trim().toLowerCase() === managerName
    );

    if (!managerEmployee?.email) {
      setMessage(`Unable to email: manager email for ${record.manager} was not found.`);
      return;
    }

    const employeeRecords = records.filter((entry) => entry.employeeId === record.employeeId);
    const summary = summaryRows.find((row) => row.employeeId === record.employeeId);

    const pendingWarningRecords = records
      .filter(
        (entry) =>
          entry.employeeId === record.employeeId &&
          entry.recordType === "WARNING" &&
          entry.appealDecision === "PENDING"
      )
      .sort(
        (first, second) =>
          first.occurrenceDate.localeCompare(second.occurrenceDate) ||
          first.id.localeCompare(second.id)
      );

    const pendingWarningIndex =
      pendingWarningRecords.findIndex((entry) => entry.id === record.id) + 1;

    const warningNumber =
      pendingWarningIndex > 0
        ? pendingWarningIndex
        : Math.max(1, pendingWarningRecords.length);

    const pendingWarningTemplates = {
      1: `Dear ${record.name},

This email is to inform you that a pending warning has been issued based on recent performance records.

Your direct manager will schedule a meeting with you to review the situation and discuss an improvement plan. The purpose of this meeting is to ensure clarity on expectations and to support your improvement moving forward.

Following the meeting, Human Resources will send you a follow-up email requesting that you submit a written improvement plan within one (1) week. This is to confirm your understanding of the areas that require improvement and the steps you will take to address them.

After reviewing your response, your direct manager will determine the outcome of this pending warning:
• Approved: Warning will be canceled
• Declined: Warning will be confirmed

Please take this process seriously and use it as an opportunity to improve your performance.

If you have any questions, please feel free to reach out.

Sincerely,
Human Resources`,
      2: `Dear ${record.name},

This email is to inform you that a second pending warning has been issued based on your performance records.

Your direct manager will schedule a meeting with you, and a Human Resources representative will also be present. This meeting will focus on reviewing your performance, discussing an improvement plan, and understanding your intentions regarding your continued role with the organization.

Following the meeting, Human Resources will request that you submit a written improvement plan and a brief statement outlining your intention to continue in your role. This response must be submitted within one (1) week.

After reviewing your response, your direct manager will determine the outcome of this pending warning:
• Approved: Warning will be canceled
• Declined: Warning will be confirmed

We strongly encourage you to approach this step thoughtfully and demonstrate your commitment to improvement.

If you have any questions, please contact Human Resources.

Sincerely,
Human Resources`,
      3: `Dear ${record.name},

This email is to inform you that a third pending warning has been issued based on your performance records.

A formal meeting will be scheduled involving your direct manager, Human Resources, and executive leadership. This meeting will review past performance issues, discuss your overall progress, and evaluate your future with the organization.

Following the meeting, a final decision will be made:
• Approved: Warning will be canceled
• Declined: Warning will be confirmed

Please note that confirmation of a third warning may result in disciplinary action, including reduction of work hours or termination of employment.

We encourage you to prepare for this meeting carefully and reflect on your performance and future plans.

If you have any questions, please contact Human Resources.

Sincerely,
Human Resources`,
    };

    const isPendingWarning =
      record.recordType === "WARNING" && record.appealDecision === "PENDING";

    const lines = [
      `Incident Report for ${record.name} (${record.employeeId})`,
      `Department: ${record.department}`,
      `Manager: ${record.manager}`,
      "",
      "Records:",
      ...employeeRecords.map(
        (entry) =>
          `- ${entry.occurrenceDate} | ${entry.recordType} | Issued By: ${entry.issuedBy} | Appeal: ${entry.appealDecision} | Status: ${getStatusFromAppealDecision(entry.appealDecision)}`
      ),
      "",
      `Confirmed Mistakes: ${summary?.confirmedMistakes ?? 0}`,
      `Confirmed Warnings: ${summary?.confirmedWarnings ?? 0}`,
      `Warnings From Mistakes (÷5): ${summary?.warningsFromMistakes ?? 0}`,
      `Total Warning Equivalent: ${summary?.totalWarningEquivalent ?? 0}`,
    ];

    const subject = isPendingWarning
      ? warningNumber === 1
        ? `Pending Warning Notice (1st): ${record.name} (${record.employeeId})`
        : warningNumber === 2
        ? `Pending Warning Notice (2nd): ${record.name} (${record.employeeId})`
        : `Pending Warning Notice (3rd): ${record.name} (${record.employeeId})`
      : `Incident Report: ${record.name} (${record.employeeId})`;

    const body = isPendingWarning
      ? warningNumber === 1
        ? pendingWarningTemplates[1]
        : warningNumber === 2
        ? pendingWarningTemplates[2]
        : pendingWarningTemplates[3]
      : lines.join("\n");

    setEmailDraft({
      incidentId: record.id,
      isFollowUp: false,
      to: employee.email,
      cc: managerEmployee.email,
      bcc: DEFAULT_BCC,
      subject,
      body,
      attachments: [],
    });
  };

  const getPendingWarningLevel = (record: IncidentRecord): number | null => {
    if (record.recordType !== "WARNING" || record.appealDecision !== "PENDING") {
      return null;
    }

    const pendingWarningRecords = records
      .filter(
        (entry) =>
          entry.employeeId === record.employeeId &&
          entry.recordType === "WARNING" &&
          entry.appealDecision === "PENDING"
      )
      .sort(
        (first, second) =>
          first.occurrenceDate.localeCompare(second.occurrenceDate) ||
          first.id.localeCompare(second.id)
      );

    const index = pendingWarningRecords.findIndex((entry) => entry.id === record.id);
    if (index === -1) return null;
    return index + 1;
  };

  const handleOpenFollowUpEmail = (record: IncidentRecord, warningLevel: 1 | 2) => {
    const employee = sortedEmployees.find((entry) => entry.id === record.employeeId);
    if (!employee?.email) {
      setMessage(`Unable to email: employee email for ${record.name} was not found.`);
      return;
    }

    const managerName = (record.manager || "").trim().toLowerCase();
    const managerEmployee = sortedEmployees.find(
      (entry) => entry.name.trim().toLowerCase() === managerName
    );

    if (!managerEmployee?.email) {
      setMessage(`Unable to email: manager email for ${record.manager} was not found.`);
      return;
    }

    const subject =
      warningLevel === 1
        ? `Follow-Up: Written Improvement Plan Request (1st Pending Warning) - ${record.name} (${record.employeeId})`
        : `Follow-Up: Written Response Request (2nd Pending Warning) - ${record.name} (${record.employeeId})`;

    const body =
      warningLevel === 1
        ? `Dear ${record.name},

Following your recent meeting with your direct manager regarding the pending warning, this is a reminder to submit your written improvement plan.

Please outline your understanding of the areas that require improvement and the specific actions you will take to address them. This plan is intended to ensure alignment between you, your manager, and Human Resources on expectations moving forward.

Kindly submit your response via email within one (1) week from the date of this notice.

If you have any questions or need clarification, please feel free to reach out.

Sincerely,
Human Resource`
        : `Dear ${record.name},

Following your recent meeting with your direct manager and Human Resources regarding the pending warning, this is a request for your written response.

Please provide:
1. A written improvement plan outlining your understanding of the areas that require improvement and the specific actions you will take.
2. A brief statement confirming your intention regarding your continued role with the organization.

This response is intended to ensure clarity and alignment on expectations and your future direction.

Kindly submit your response via email within one (1) week from the date of this notice.

If you have any questions or need clarification, please feel free to contact Human Resources.

Sincerely,
Human Resources`;

    setEmailDraft({
      incidentId: record.id,
      isFollowUp: true,
      to: employee.email,
      cc: managerEmployee.email,
      bcc: DEFAULT_BCC,
      subject,
      body,
      attachments: [],
    });
  };

  const handleSendEmailDraft = async () => {
    if (!emailDraft) return;

    try {
      setSendingEmail(true);
      setMessage("");

      const formData = new FormData();
      formData.append("to", emailDraft.to);
      formData.append("cc", emailDraft.cc);
      formData.append("bcc", emailDraft.bcc);
      formData.append("subject", emailDraft.subject);
      formData.append("body", emailDraft.body);
      for (const file of emailDraft.attachments) {
        formData.append("attachments", file);
      }

      const response = await fetch("/api/email/send", {
        method: "POST",
        body: formData,
      });

      const payload = await response.json().catch(() => ({}));
      if (!response.ok) {
        throw new Error(payload?.error || "Failed to send email");
      }

      const incidentResponse = await fetch(`/api/incidents/${emailDraft.incidentId}`, {
        method: "PATCH",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify(
          emailDraft.isFollowUp
            ? { followUpEmailSent: true }
            : { emailSent: true }
        ),
      });

      const incidentPayload = await incidentResponse.json().catch(() => ({}));
      if (!incidentResponse.ok) {
        throw new Error(incidentPayload?.details || incidentPayload?.error || "Failed to save email status");
      }

      if (emailDraft.isFollowUp) {
        setReviewDrafts((previous) => {
          const existing = previous[emailDraft.incidentId];
          if (!existing) return previous;

          return {
            ...previous,
            [emailDraft.incidentId]: {
              ...existing,
              followUpEmailSent: true,
            },
          };
        });
      } else {
        setReviewDrafts((previous) => {
          const existing = previous[emailDraft.incidentId];
          if (!existing) return previous;

          return {
            ...previous,
            [emailDraft.incidentId]: {
              ...existing,
              emailSent: true,
            },
          };
        });
      }

      setMessage(`Email sent successfully to ${emailDraft.to}.`);
      setEmailDraft(null);
    } catch (error) {
      console.error(error);
      setMessage(error instanceof Error ? error.message : "Failed to send email.");
    } finally {
      setSendingEmail(false);
    }
  };

  const summaryRows = useMemo(() => {
    const byEmployee = new Map<
      string,
      {
        employeeId: string;
        name: string;
        department: string;
        confirmedMistakes: number;
        confirmedWarnings: number;
      }
    >();

    for (const record of records) {
      const existing =
        byEmployee.get(record.employeeId) ||
        {
          employeeId: record.employeeId,
          name: record.name,
          department: record.department,
          confirmedMistakes: 0,
          confirmedWarnings: 0,
        };

      if (record.status === "CONFIRMED" && record.recordType === "MISTAKE") {
        existing.confirmedMistakes += 1;
      }

      if (
        record.recordType === "WARNING" &&
        record.status === "CONFIRMED" &&
        record.appealDecision === "DECLINED"
      ) {
        existing.confirmedWarnings += 1;
      }

      byEmployee.set(record.employeeId, existing);
    }

    return [...byEmployee.values()]
      .map((row) => {
        const warningsFromMistakes = Math.floor(row.confirmedMistakes / 5);
        const totalWarningEquivalent = row.confirmedWarnings + warningsFromMistakes;
        return {
          ...row,
          warningsFromMistakes,
          totalWarningEquivalent,
          requiresDisciplinaryAction: totalWarningEquivalent >= 3,
        };
      })
      .sort((a, b) =>
        a.employeeId.localeCompare(b.employeeId, undefined, {
          numeric: true,
          sensitivity: "base",
        })
      );
  }, [records]);

  const editingRecord =
    editingRecordId != null
      ? records.find((record) => record.id === editingRecordId) || null
      : null;

  const filteredRecords = useMemo(() => {
    const scopedRecords = selectedEmployeeFilter
      ? records.filter((record) => record.employeeId === selectedEmployeeFilter)
      : records;

    return [...scopedRecords].sort((first, second) => {
      const byName = first.name.localeCompare(second.name, undefined, {
        sensitivity: "base",
      });
      if (byName !== 0) return byName;

      const byEmployeeId = first.employeeId.localeCompare(second.employeeId, undefined, {
        numeric: true,
        sensitivity: "base",
      });
      if (byEmployeeId !== 0) return byEmployeeId;

      const byDate = second.occurrenceDate.localeCompare(first.occurrenceDate);
      if (byDate !== 0) return byDate;

      return second.id.localeCompare(first.id);
    });
  }, [records, selectedEmployeeFilter]);

  useEffect(() => {
    if (savingId) return;

    for (const record of filteredRecords) {
      const warningLevel = getPendingWarningLevel(record);
      if (warningLevel !== 1 && warningLevel !== 2 && warningLevel !== 3) {
        continue;
      }

      const draft = reviewDrafts[record.id];
      if (!draft) {
        continue;
      }

      const signature = `${warningLevel}|${draft.meetingCompleted}|${draft.appealDecision}|${draft.finalAction}|${draft.decisionDate}|${draft.emailSent}|${draft.followUpEmailSent}|${draft.improvementPlanReceived}`;
      const previousSignature = autoSavedPendingWarning[record.id];

      if (!previousSignature) {
        setAutoSavedPendingWarning((previous) => ({
          ...previous,
          [record.id]: signature,
        }));
        continue;
      }

      if (previousSignature === signature) {
        continue;
      }

      setAutoSavedPendingWarning((previous) => ({
        ...previous,
        [record.id]: signature,
      }));
      void handleReviewSave(record.id);
      break;
    }
  }, [filteredRecords, reviewDrafts, autoSavedPendingWarning, savingId]);

  useEffect(() => {
    if (editingRecordId && editSectionRef.current) {
      editSectionRef.current.scrollIntoView({ behavior: "smooth", block: "start" });
    }
  }, [editingRecordId]);

  return (
    <div className="space-y-6">
      <div className="bg-white rounded-lg shadow-md p-6">
        <div className="flex items-center justify-between">
          <h3 className="text-xl font-bold text-gray-900">Incident Management</h3>
          <button
            onClick={() => setShowCreateForm((previous) => !previous)}
            className="bg-blue-400 text-white font-semibold py-2 px-5 rounded-lg hover:bg-blue-500"
          >
            {showCreateForm ? "Close Add Incident" : "Add Mistake / Warning Incident"}
          </button>
        </div>
      </div>

      {showCreateForm && (
      <div className="bg-white rounded-lg shadow-md p-6">
        <h3 className="text-xl font-bold text-gray-900 mb-4">Add Mistake / Warning Incident</h3>
        <div className="grid grid-cols-1 md:grid-cols-3 gap-4">
          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1">Employee *</label>
            <select
              value={employeeId}
              onChange={(event) => {
                setEmployeeId(event.target.value);
                const employee = employees.find((entry) => entry.id === event.target.value);
                if (employee) {
                  setManager(employee.manager || "");
                }
              }}
              className="w-full px-3 py-2 border border-blue-300 rounded-lg bg-blue-50"
            >
              <option value="">Select employee...</option>
              {sortedEmployees.map((employee) => (
                <option key={employee.id} value={employee.id}>
                  {employee.name} ({employee.id})
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1">Manager *</label>
            <input
              value={manager}
              onChange={(event) => setManager(event.target.value)}
              placeholder="Manager name"
              className="w-full px-3 py-2 border border-blue-300 rounded-lg"
            />
          </div>

          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1">Issued By *</label>
            <select
              value={issuedBy}
              onChange={(event) => setIssuedBy(event.target.value)}
              className="w-full px-3 py-2 border border-blue-300 rounded-lg bg-blue-50"
            >
              <option value="">Select position...</option>
              {positionOptions.map((position) => (
                <option key={`issuer-position-${position}`} value={position}>
                  {position}
                </option>
              ))}
            </select>
          </div>

          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1">Record Type *</label>
            <select
              value={recordType}
              onChange={(event) => setRecordType(event.target.value as RecordType)}
              className="w-full px-3 py-2 border border-blue-300 rounded-lg bg-blue-50"
            >
              <option value="MISTAKE">MISTAKE</option>
              <option value="WARNING">WARNING</option>
            </select>
          </div>

          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1">Occurrence Date *</label>
            <input
              type="date"
              value={occurrenceDate}
              onChange={(event) => setOccurrenceDate(event.target.value)}
              className="w-full px-3 py-2 border border-blue-300 rounded-lg"
            />
          </div>

          <div>
            <label className="block text-sm font-semibold text-gray-700 mb-1">Status</label>
            <input
              value="PENDING"
              disabled
              className="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-100 text-gray-600"
            />
          </div>
        </div>

        <div className="mt-4">
          <label className="block text-sm font-semibold text-gray-700 mb-1">Reason *</label>
          <textarea
            value={reason}
            onChange={(event) => setReason(event.target.value)}
            rows={3}
            placeholder="Describe what caused this mistake or warning"
            className="w-full px-3 py-2 border border-blue-300 rounded-lg"
          />
        </div>

        <div className="mt-4">
          <label className="block text-sm font-semibold text-gray-700 mb-1">Initial Memo (optional)</label>
          <textarea
            value={historyMemo}
            onChange={(event) => setHistoryMemo(event.target.value)}
            rows={3}
            placeholder="Add note, appeal context, or manager comment"
            className="w-full px-3 py-2 border border-blue-300 rounded-lg"
          />
        </div>

        <div className="mt-4 flex items-center gap-4">
          <button
            onClick={handleCreateRecord}
            disabled={loading}
            className="bg-blue-400 text-white font-semibold py-2 px-5 rounded-lg hover:bg-blue-500 disabled:opacity-50"
          >
            Save Incident
          </button>
          {selectedEmployee && (
            <p className="text-sm text-gray-600">
              Selected: {selectedEmployee.name} • {selectedEmployee.department}
            </p>
          )}
        </div>

        {message && <p className="mt-3 text-sm text-gray-700">{message}</p>}
      </div>
      )}

      {editingRecord && reviewDrafts[editingRecord.id] && (
        <div ref={editSectionRef} className="bg-white rounded-lg shadow-md p-6 border border-purple-200">
          <div className="flex items-center justify-between mb-4">
            <h3 className="text-xl font-bold text-gray-900">Edit Incident Record</h3>
            <button
              onClick={() => setEditingRecordId(null)}
              className="px-4 py-2 rounded-lg border border-gray-300 text-gray-700 hover:bg-gray-50"
            >
              Close
            </button>
          </div>

          <div className="grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1">Employee</label>
              <input
                value={`${editingRecord.name} (${editingRecord.employeeId})`}
                disabled
                className="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-100 text-gray-600"
              />
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1">Manager</label>
              <input
                value={reviewDrafts[editingRecord.id].manager}
                onChange={(event) =>
                  setReviewDrafts((previous) => ({
                    ...previous,
                    [editingRecord.id]: {
                      ...previous[editingRecord.id],
                      manager: event.target.value,
                    },
                  }))
                }
                className="w-full px-3 py-2 border border-blue-300 rounded-lg"
              />
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1">Record Type</label>
              <select
                value={reviewDrafts[editingRecord.id].recordType}
                onChange={(event) =>
                  setReviewDrafts((previous) => ({
                    ...previous,
                    [editingRecord.id]: {
                      ...previous[editingRecord.id],
                      recordType: event.target.value as RecordType,
                    },
                  }))
                }
                className="w-full px-3 py-2 border border-blue-300 rounded-lg bg-blue-50"
              >
                <option value="MISTAKE">MISTAKE</option>
                <option value="WARNING">WARNING</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1">Occurrence Date</label>
              <input
                type="date"
                value={reviewDrafts[editingRecord.id].occurrenceDate || ""}
                onChange={(event) =>
                  setReviewDrafts((previous) => ({
                    ...previous,
                    [editingRecord.id]: {
                      ...previous[editingRecord.id],
                      occurrenceDate: event.target.value,
                    },
                  }))
                }
                className="w-full px-3 py-2 border border-blue-300 rounded-lg"
              />
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1">Issued By</label>
              <select
                value={reviewDrafts[editingRecord.id].issuedBy}
                onChange={(event) =>
                  setReviewDrafts((previous) => ({
                    ...previous,
                    [editingRecord.id]: {
                      ...previous[editingRecord.id],
                      issuedBy: event.target.value,
                    },
                  }))
                }
                className="w-full px-3 py-2 border border-blue-300 rounded-lg bg-blue-50"
              >
                <option value="">Select position...</option>
                {positionOptions.map((position) => (
                  <option key={`issuer-edit-position-${position}`} value={position}>
                    {position}
                  </option>
                ))}
              </select>
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1">Appeal Decision</label>
              <select
                value={reviewDrafts[editingRecord.id].appealDecision}
                onChange={(event) => {
                  const nextDecision = event.target.value as AppealDecision;
                  setReviewDrafts((previous) => ({
                    ...previous,
                    [editingRecord.id]: {
                      ...previous[editingRecord.id],
                      appealDecision: nextDecision,
                      status: getStatusFromAppealDecision(nextDecision),
                    },
                  }));
                }}
                className="w-full px-3 py-2 border border-blue-300 rounded-lg bg-blue-50"
              >
                <option value="PENDING">PENDING</option>
                <option value="DECLINED">DECLINED</option>
                <option value="APPROVED">APPROVED</option>
              </select>
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1">Status</label>
              <input
                value={reviewDrafts[editingRecord.id].status}
                disabled
                className="w-full px-3 py-2 border border-gray-300 rounded-lg bg-gray-100 text-gray-600"
              />
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1">Decision Date</label>
              <input
                type="date"
                value={reviewDrafts[editingRecord.id].decisionDate || ""}
                onChange={(event) =>
                  setReviewDrafts((previous) => ({
                    ...previous,
                    [editingRecord.id]: {
                      ...previous[editingRecord.id],
                      decisionDate: event.target.value,
                    },
                  }))
                }
                className="w-full px-3 py-2 border border-blue-300 rounded-lg"
              />
            </div>
          </div>

          <div className="mt-4">
            <label className="block text-sm font-semibold text-gray-700 mb-1">Reason</label>
            <textarea
              rows={3}
              value={reviewDrafts[editingRecord.id].reason}
              onChange={(event) =>
                setReviewDrafts((previous) => ({
                  ...previous,
                  [editingRecord.id]: {
                    ...previous[editingRecord.id],
                    reason: event.target.value,
                  },
                }))
              }
              className="w-full px-3 py-2 border border-blue-300 rounded-lg"
            />
          </div>

          <div className="mt-4 grid grid-cols-1 md:grid-cols-2 gap-4">
            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1">Reviewed By</label>
              <input
                value={reviewDrafts[editingRecord.id].reviewedBy}
                onChange={(event) =>
                  setReviewDrafts((previous) => ({
                    ...previous,
                    [editingRecord.id]: {
                      ...previous[editingRecord.id],
                      reviewedBy: event.target.value,
                    },
                  }))
                }
                className="w-full px-3 py-2 border border-blue-300 rounded-lg"
              />
            </div>

            <div>
              <label className="block text-sm font-semibold text-gray-700 mb-1">Final Action</label>
              <select
                value={reviewDrafts[editingRecord.id].finalAction}
                onChange={(event) =>
                  setReviewDrafts((previous) => ({
                    ...previous,
                    [editingRecord.id]: {
                      ...previous[editingRecord.id],
                      finalAction: event.target.value as FinalAction,
                    },
                  }))
                }
                className="w-full px-3 py-2 border border-blue-300 rounded-lg bg-blue-50"
              >
                <option value="NONE">NONE</option>
                <option value="HOUR_REDUCTION">HOUR_REDUCTION</option>
                <option value="TERMINATION">TERMINATION</option>
              </select>
            </div>
          </div>

          <div className="mt-4">
            <label className="block text-sm font-semibold text-gray-700 mb-1">Memo</label>
            <textarea
              rows={3}
              value={reviewDrafts[editingRecord.id].note}
              onChange={(event) =>
                setReviewDrafts((previous) => ({
                  ...previous,
                  [editingRecord.id]: {
                    ...previous[editingRecord.id],
                    note: event.target.value,
                  },
                }))
              }
              placeholder="Add edit/review notes"
              className="w-full px-3 py-2 border border-blue-300 rounded-lg"
            />
          </div>

          <div className="mt-4 flex gap-3">
            <button
              onClick={() => handleReviewSave(editingRecord.id)}
              disabled={savingId === editingRecord.id}
              className="bg-purple-400 text-white px-4 py-2 rounded-lg hover:bg-purple-500 disabled:opacity-50"
            >
              {savingId === editingRecord.id ? "Saving..." : "Save Changes"}
            </button>
            <button
              onClick={() => setEditingRecordId(null)}
              className="bg-gray-300 text-gray-800 px-4 py-2 rounded-lg hover:bg-gray-400"
            >
              Cancel
            </button>
          </div>
        </div>
      )}

      <div className="bg-white rounded-lg shadow-md overflow-hidden">
        <div className="px-6 py-4 border-b bg-gray-50">
          <h3 className="text-lg font-bold text-gray-900">Incident Records and Totals</h3>
          <p className="text-sm text-gray-600">
            Confirmed totals only: every 5 confirmed mistakes auto-generates 1 warning; 3 confirmed warnings flags disciplinary action.
          </p>
          <div className="mt-3 flex flex-wrap items-end gap-3">
            <div className="max-w-sm">
              <label className="block text-sm font-semibold text-gray-700 mb-1">Filter by Employee</label>
              <select
                value={selectedEmployeeFilter}
                onChange={(event) => setSelectedEmployeeFilter(event.target.value)}
                className="w-full px-3 py-2 border border-blue-300 rounded-lg bg-blue-50"
              >
                <option value="">All Employees</option>
                {sortedEmployees.map((employee) => (
                  <option key={`filter-${employee.id}`} value={employee.id}>
                    {employee.name} ({employee.id})
                  </option>
                ))}
              </select>
            </div>
            <button
              onClick={handlePrintIncidentReport}
              className="bg-gray-700 text-white text-sm font-semibold px-3 py-2 rounded-lg hover:bg-gray-800"
            >
              Print PDF (Landscape)
            </button>
          </div>
        </div>

        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-gray-100 border-b">
              <tr>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Employee Name</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Department</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Manager</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Record Type</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Occurrence Date</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Issued By</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Appeal Decision</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Decision Date</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Status</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Actions</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {filteredRecords.map((record) => {
                const draft = reviewDrafts[record.id] || {
                  manager: record.manager,
                  recordType: record.recordType,
                  occurrenceDate: record.occurrenceDate,
                  issuedBy: record.issuedBy,
                  reason: record.reason,
                  status: getStatusFromAppealDecision(record.appealDecision),
                  appealDecision: record.appealDecision,
                  finalAction: record.finalAction,
                  meetingCompleted: record.meetingCompleted,
                  emailSent: record.emailSent,
                  followUpEmailSent: record.followUpEmailSent,
                  improvementPlanReceived: record.improvementPlanReceived,
                  reviewedBy: record.reviewedBy,
                  decisionDate: record.decisionDate,
                  note: "",
                };

                const pendingWarningLevel = getPendingWarningLevel(record);
                const showMeetingCheckbox =
                  pendingWarningLevel === 1 ||
                  pendingWarningLevel === 2 ||
                  pendingWarningLevel === 3;
                const showFollowUpEmail = pendingWarningLevel === 1 || pendingWarningLevel === 2;
                const showImprovementPlanCheckbox =
                  showFollowUpEmail && draft.followUpEmailSent;
                const isMeetingChecked = !!draft.meetingCompleted;
                const showFinalActionInline = pendingWarningLevel === 3 && isMeetingChecked;
                const meetingLabel =
                  pendingWarningLevel === 1
                    ? "Met with direct manager"
                    : pendingWarningLevel === 2
                    ? "Met with direct manager and HR"
                    : "Met with direct manager, HR, and executive leadership";

                return (
                  <tr key={record.id} className="hover:bg-gray-50 align-top">
                    <td className="px-4 py-3 whitespace-nowrap text-gray-900">{record.name}</td>
                    <td className="px-4 py-3 whitespace-nowrap text-gray-700">{record.department}</td>
                    <td className="px-4 py-3 whitespace-nowrap text-gray-700">{record.manager}</td>
                    <td className="px-4 py-3 whitespace-nowrap">
                      <span className={`px-2 py-1 rounded text-xs font-semibold ${record.recordType === "MISTAKE" ? "bg-amber-100 text-amber-700" : "bg-red-100 text-red-700"}`}>
                        {record.recordType}
                      </span>
                      {record.isAutoGenerated && (
                        <span className="ml-2 px-2 py-1 rounded text-xs font-semibold bg-purple-100 text-purple-700">
                          AUTO
                        </span>
                      )}
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap text-gray-700">{formatShortDate(record.occurrenceDate)}</td>
                    <td className="px-4 py-3 whitespace-nowrap text-gray-700">{record.issuedBy}</td>
                    <td className="px-4 py-3 whitespace-nowrap text-gray-700">
                      <select
                        value={draft.appealDecision}
                        onChange={(event) => {
                          const nextDecision = event.target.value as AppealDecision;
                          const nextDraft = {
                            ...draft,
                            appealDecision: nextDecision,
                            status: getStatusFromAppealDecision(nextDecision),
                          };

                          setReviewDrafts((previous) => ({
                            ...previous,
                            [record.id]: nextDraft,
                          }));

                          void handleReviewSave(record.id, nextDraft);
                        }}
                        className="px-2 py-1 border border-blue-300 rounded bg-blue-50"
                      >
                        <option value="PENDING">PENDING</option>
                        <option value="DECLINED">DECLINED</option>
                        <option value="APPROVED">APPROVED</option>
                      </select>
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap text-gray-700">
                      <input
                        type="date"
                        value={draft.decisionDate || ""}
                        onChange={(event) =>
                          setReviewDrafts((previous) => ({
                            ...previous,
                            [record.id]: {
                              ...draft,
                              decisionDate: event.target.value,
                            },
                          }))
                        }
                        className="px-2 py-1 border border-blue-300 rounded"
                      />
                    </td>
                    <td className="px-4 py-3 whitespace-nowrap text-gray-700">{draft.status}</td>
                    <td className="px-4 py-3 min-w-44">
                      {showMeetingCheckbox && (
                        <label className="mb-2 flex items-center gap-2 text-xs text-gray-700">
                          <input
                            type="checkbox"
                            checked={isMeetingChecked}
                            onChange={(event) =>
                              setReviewDrafts((previous) => ({
                                ...previous,
                                [record.id]: {
                                  ...draft,
                                  meetingCompleted: event.target.checked,
                                },
                              }))
                            }
                          />
                          {meetingLabel}
                        </label>
                      )}

                      {showFinalActionInline && (
                        <div className="mb-2">
                          <label className="block text-xs font-semibold text-gray-700 mb-1">
                            Final Action
                          </label>
                          <select
                            value={draft.finalAction}
                            onChange={(event) =>
                              setReviewDrafts((previous) => ({
                                ...previous,
                                [record.id]: {
                                  ...draft,
                                  finalAction: event.target.value as FinalAction,
                                },
                              }))
                            }
                            className="w-full px-2 py-1 border border-blue-300 rounded bg-blue-50 text-xs"
                          >
                            <option value="NONE">NONE</option>
                            <option value="HOUR_REDUCTION">HOUR_REDUCTION</option>
                            <option value="TERMINATION">TERMINATION</option>
                          </select>
                        </div>
                      )}

                      {showImprovementPlanCheckbox && (
                        <label className="mb-2 flex items-center gap-2 text-xs text-gray-700">
                          <input
                            type="checkbox"
                            checked={!!draft.improvementPlanReceived}
                            onChange={(event) =>
                              setReviewDrafts((previous) => ({
                                ...previous,
                                [record.id]: {
                                  ...draft,
                                  improvementPlanReceived: event.target.checked,
                                },
                              }))
                            }
                          />
                          Received employee improvement plan
                        </label>
                      )}

                      <div className="flex flex-wrap gap-2">
                        <button
                          onClick={() => setEditingRecordId(record.id)}
                          className="bg-purple-400 text-white text-xs px-2 py-1 rounded hover:bg-purple-500"
                        >
                          Edit
                        </button>
                        <button
                          onClick={() => handleDeleteRecord(record.id)}
                          disabled={savingId === record.id}
                          className="bg-red-400 text-white text-xs px-2 py-1 rounded hover:bg-red-500 disabled:opacity-50"
                        >
                          Delete
                        </button>
                        <button
                          onClick={() => handleEmailIncidentReport(record)}
                          disabled={savingId === record.id || draft.emailSent}
                          className={`text-white text-xs px-2 py-1 rounded ${
                            draft.emailSent
                              ? "bg-gray-400 cursor-not-allowed"
                              : "bg-emerald-500 hover:bg-emerald-600"
                          } disabled:opacity-50`}
                        >
                          {draft.emailSent ? "Email Sent" : "Email"}
                        </button>
                        {showFollowUpEmail && isMeetingChecked && (
                          <button
                            onClick={() =>
                              handleOpenFollowUpEmail(record, pendingWarningLevel === 1 ? 1 : 2)
                            }
                            disabled={draft.followUpEmailSent}
                            className={`text-white text-xs px-2 py-1 rounded ${
                              draft.followUpEmailSent
                                ? "bg-gray-400 cursor-not-allowed"
                                : "bg-indigo-500 hover:bg-indigo-600"
                            }`}
                          >
                            {draft.followUpEmailSent ? "Follow-up Sent" : "Follow-up Email"}
                          </button>
                        )}
                      </div>
                    </td>
                  </tr>
                );
              })}

              {filteredRecords.length === 0 && !loading && (
                <tr>
                  <td colSpan={10} className="px-4 py-8 text-center text-gray-600">
                    No incident records yet.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>
      </div>

      <div className="bg-white rounded-lg shadow-md overflow-hidden">
        <div className="px-6 py-4 border-b bg-gray-50">
          <h3 className="text-lg font-bold text-gray-900">Incident Summary</h3>
          <p className="text-sm text-gray-600">
            Confirmed totals only. Every 5 confirmed mistakes is counted as 1 warning equivalent.
          </p>
        </div>
        <div className="overflow-x-auto">
          <table className="w-full text-sm">
            <thead className="bg-gray-100 border-b">
              <tr>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Employee</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Department</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Confirmed Mistakes</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Confirmed Warnings</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Warnings From Mistakes (÷5)</th>
                <th className="px-4 py-3 text-left font-semibold text-gray-700">Total Warning Equivalent</th>
              </tr>
            </thead>
            <tbody className="divide-y divide-gray-200">
              {summaryRows.map((row) => (
                <tr key={`summary-${row.employeeId}`}>
                  <td className="px-4 py-3 text-gray-900">
                    {row.name} ({row.employeeId})
                  </td>
                  <td className="px-4 py-3 text-gray-700">{row.department}</td>
                  <td className="px-4 py-3 text-gray-700">{row.confirmedMistakes}</td>
                  <td className="px-4 py-3 text-gray-700">{row.confirmedWarnings}</td>
                  <td className="px-4 py-3 text-gray-700">{row.warningsFromMistakes}</td>
                  <td className="px-4 py-3">
                    <span
                      className={`font-semibold ${
                        row.totalWarningEquivalent >= 3 ? "text-red-600" : "text-gray-700"
                      }`}
                    >
                      {row.totalWarningEquivalent}
                    </span>
                  </td>
                </tr>
              ))}

              {summaryRows.length === 0 && (
                <tr>
                  <td colSpan={6} className="px-4 py-8 text-center text-gray-600">
                    No summary data available.
                  </td>
                </tr>
              )}
            </tbody>
          </table>
        </div>

        {/* Email Draft Modal */}
        {emailDraft && (
          <div className="fixed inset-0 bg-black bg-opacity-50 flex items-center justify-center z-50">
            <div className="bg-white rounded-lg shadow-lg max-w-2xl w-full mx-4 p-6">
              <h2 className="text-xl font-bold mb-4">Edit Email</h2>
              
              <div className="mb-4">
                <label className="block text-sm font-semibold mb-1">To:</label>
                <input
                  type="text"
                  value={emailDraft.to}
                  onChange={(e) => setEmailDraft({ ...emailDraft, to: e.target.value })}
                  className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
                />
              </div>

              <div className="mb-4">
                <label className="block text-sm font-semibold mb-1">BCC:</label>
                <input
                  type="text"
                  value={emailDraft.bcc}
                  onChange={(e) => setEmailDraft({ ...emailDraft, bcc: e.target.value })}
                  className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
                />
              </div>

              <div className="mb-4">
                <label className="block text-sm font-semibold mb-1">CC:</label>
                <input
                  type="text"
                  value={emailDraft.cc}
                  onChange={(e) => setEmailDraft({ ...emailDraft, cc: e.target.value })}
                  className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
                />
              </div>

              <div className="mb-4">
                <label className="block text-sm font-semibold mb-1">Subject:</label>
                <input
                  type="text"
                  value={emailDraft.subject}
                  onChange={(e) => setEmailDraft({ ...emailDraft, subject: e.target.value })}
                  className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
                />
              </div>

              <div className="mb-6">
                <label className="block text-sm font-semibold mb-1">Body:</label>
                <textarea
                  value={emailDraft.body}
                  onChange={(e) => setEmailDraft({ ...emailDraft, body: e.target.value })}
                  rows={10}
                  className="w-full border border-gray-300 rounded px-3 py-2 text-sm font-mono"
                />
              </div>

              <div className="mb-6">
                <label className="block text-sm font-semibold mb-1">Attachments:</label>
                <input
                  type="file"
                  multiple
                  onChange={(event) =>
                    setEmailDraft({
                      ...emailDraft,
                      attachments: Array.from(event.target.files || []),
                    })
                  }
                  className="w-full border border-gray-300 rounded px-3 py-2 text-sm"
                />
                {emailDraft.attachments.length > 0 && (
                  <p className="mt-2 text-xs text-gray-600">
                    {emailDraft.attachments.map((file) => file.name).join(", ")}
                  </p>
                )}
              </div>

              <div className="flex gap-2 justify-end">
                <button
                  onClick={() => setEmailDraft(null)}
                  className="px-4 py-2 bg-gray-300 text-gray-800 rounded hover:bg-gray-400"
                  disabled={sendingEmail}
                >
                  Cancel
                </button>
                <button
                  onClick={handleSendEmailDraft}
                  className="px-4 py-2 bg-blue-500 text-white rounded hover:bg-blue-600 disabled:bg-gray-400"
                  disabled={sendingEmail}
                >
                  {sendingEmail ? "Sending..." : "Send Email"}
                </button>
              </div>
            </div>
          </div>
        )}
      </div>
    </div>
  );
}
