"use client";

import { Employee, WeeklyRecord } from "@/lib/employees";
import { calculateWeeklyPerformanceScore, getPerformanceRating, getPerformanceColor, getPerformanceBgColor } from "@/lib/performanceScoring";
import { formatDateInPacific } from "@/lib/dateUtils";
import { useState, useRef } from "react";

interface MonthlyPerformanceReportProps {
  employee: Employee;
  year: number;
  month: number;
}

export default function MonthlyPerformanceReport({
  employee,
  year,
  month,
}: MonthlyPerformanceReportProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [monthlyComment, setMonthlyComment] = useState<string>("");
  const [generateMessage, setGenerateMessage] = useState<string | null>(null);
  const autoGeneratedRef = useRef(false);

  const monthNames = [
    "January", "February", "March", "April", "May", "June",
    "July", "August", "September", "October", "November", "December"
  ];

  // Filter records for the selected month/year
  const monthlyRecords = employee.weeklyRecords.filter((record) => {
    const startDate = new Date(`${record.startDate}T12:00:00`);
    return (
      startDate.getFullYear() === year &&
      startDate.getMonth() === month
    );
  });

  // Calculate weekly scores
  const weeklyScores = monthlyRecords.map((record) => {
    const score = calculateWeeklyPerformanceScore(record);
    return {
      record,
      totalScore: score.totalScore,
      rating: getPerformanceRating(score.totalScore),
      breakdown: score,
    };
  });

  // Calculate monthly average
  const monthlyAverage = weeklyScores.length > 0
    ? Math.round(weeklyScores.reduce((sum, ws) => sum + ws.totalScore, 0) / weeklyScores.length * 100) / 100
    : 0;

  const monthlyRating = getPerformanceRating(monthlyAverage);
  const textColor = getPerformanceColor(monthlyAverage);
  const bgColor = getPerformanceBgColor(monthlyAverage);

  // Performance trend analysis
  const getTrend = () => {
    if (weeklyScores.length < 2) return "Insufficient data";
    
    const scores = weeklyScores.map(ws => ws.totalScore);
    const firstHalf = scores.slice(0, Math.ceil(scores.length / 2));
    const secondHalf = scores.slice(Math.ceil(scores.length / 2));
    
    const firstAvg = firstHalf.reduce((a, b) => a + b, 0) / firstHalf.length;
    const secondAvg = secondHalf.reduce((a, b) => a + b, 0) / secondHalf.length;
    
    const diff = secondAvg - firstAvg;
    
    if (Math.abs(diff) < 3) return "Stable";
    if (diff > 0) return `Improving (+${diff.toFixed(1)})`;
    return `Declining (${diff.toFixed(1)})`;
  };

  const handlePrint = () => {
    window.print();
  };

  const generateMonthlyComment = async () => {
    if (weeklyScores.length === 0) {
      setGenerateMessage("No weekly records found for this month.");
      return;
    }

    setIsGenerating(true);
    setGenerateMessage(null);
    autoGeneratedRef.current = true;

    try {
      const response = await fetch("/api/ai/monthly-comment", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          employeeName: employee.name,
          employeeId: employee.id,
          year,
          month,
          monthName: monthNames[month],
          weeklyScores: weeklyScores.map(ws => ({
            startDate: ws.record.startDate,
            endDate: ws.record.endDate,
            totalScore: ws.totalScore,
            rating: ws.rating,
            breakdown: ws.breakdown,
          })),
          monthlyAverage,
          monthlyRating,
          workAuthorizationStatus: employee.workAuthorizationStatus,
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        let errorPayload: any = null;
        try {
          errorPayload = JSON.parse(errorText);
        } catch {
          errorPayload = null;
        }

        if (errorPayload?.error === "GEMINI_QUOTA_EXCEEDED" || errorPayload?.error === "GEMINI_SERVICE_UNAVAILABLE") {
          const fallback = buildFallbackComment();
          setMonthlyComment(fallback);
          const message = errorPayload?.error === "GEMINI_QUOTA_EXCEEDED"
            ? "AI quota reached. A local fallback comment was generated."
            : "AI service temporarily unavailable. A local fallback comment was generated.";
          setGenerateMessage(message);
          return;
        }

        setGenerateMessage("AI generation failed. Please try again later.");
        console.error("AI monthly comment generation failed:", errorText);
        return;
      }

      const data = await response.json();
      const generated = data?.comment?.trim();
      if (generated) {
        setMonthlyComment(generated);
        setGenerateMessage("AI comment generated successfully.");
      }
    } catch (error) {
      console.error("Error generating monthly comment:", error);
      setGenerateMessage("AI generation failed. Please try again later.");
    } finally {
      setIsGenerating(false);
    }
  };

  const buildFallbackComment = () => {
    const trend = getTrend();
    const avgScore = monthlyAverage.toFixed(2);
    const weekCount = weeklyScores.length;
    
    if (monthlyAverage < 70) {
      return (
        `Your monthly average score for ${monthNames[month]} ${year} is ${avgScore}, which is below expectation. ` +
        `Based on ${weekCount} week(s) of data, your performance trend is ${trend}. ` +
        `This requires immediate improvement across all evaluation areas.\n\n` +
        `Critical areas needing attention: consistent work hour tracking, reducing overdue tasks, and improving task completion rates. ` +
        `Review each weekly evaluation to identify specific patterns and take corrective action immediately.`
      );
    }

    return (
      `Your monthly average score for ${monthNames[month]} ${year} is ${avgScore} (${monthlyRating}). ` +
      `Based on ${weekCount} week(s) of data, your performance trend shows ${trend}. ` +
      `Overall, you are meeting expectations with room for growth.\n\n` +
      `Continue your current performance level while focusing on areas flagged in individual weekly evaluations. ` +
      `Consistent execution and proactive task management will help maintain or improve your monthly average.`
    );
  };

  if (monthlyRecords.length === 0) {
    return (
      <div className="bg-white rounded-lg shadow-md p-6">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          Monthly Performance Report
        </h2>
        <p className="text-gray-600">
          No weekly records found for {monthNames[month]} {year}.
        </p>
      </div>
    );
  }

  return (
    <>
      <style jsx global>{`
        @media print {
          @page {
            size: A4;
            margin: 1.5cm;
          }
          
          * {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            color-adjust: exact !important;
          }
          
          .print-avoid-break {
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }
          
          button {
            display: none !important;
          }
        }
      `}</style>
      <div className={`rounded-lg shadow-md p-6 ${bgColor} print:shadow-none`}>
        <div className="mb-6 flex justify-between items-start">
          <div>
            <h2 className="text-2xl font-bold text-gray-900 mb-2">
              Monthly Performance Report
            </h2>
            <p className="text-sm text-gray-600">
              {employee.name} • {employee.id} • {monthNames[month]} {year}
            </p>
          </div>
          <button
            onClick={handlePrint}
            className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2 print:hidden"
            type="button"
          >
            <svg
              xmlns="http://www.w3.org/2000/svg"
              className="h-5 w-5"
              fill="none"
              viewBox="0 0 24 24"
              stroke="currentColor"
            >
              <path
                strokeLinecap="round"
                strokeLinejoin="round"
                strokeWidth={2}
                d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"
              />
            </svg>
            Print PDF
          </button>
        </div>

        {/* Monthly Summary Card */}
        <div className="bg-white rounded-lg p-6 mb-6 border-l-4 border-l-blue-500 print:border print:border-gray-300 print-avoid-break">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <p className="text-sm font-semibold text-gray-600 uppercase mb-2">
                Monthly Average
              </p>
              <p className={`text-4xl font-bold ${textColor}`}>
                {monthlyAverage.toFixed(2)}
              </p>
              <p className={`text-sm font-semibold mt-1 ${textColor}`}>
                {monthlyRating}
              </p>
            </div>
            <div>
              <p className="text-sm font-semibold text-gray-600 uppercase mb-2">
                Weeks Evaluated
              </p>
              <p className="text-4xl font-bold text-gray-900">
                {weeklyScores.length}
              </p>
            </div>
            <div>
              <p className="text-sm font-semibold text-gray-600 uppercase mb-2">
                Performance Trend
              </p>
              <p className="text-2xl font-bold text-gray-900">
                {getTrend()}
              </p>
            </div>
          </div>
        </div>

        {/* Weekly Scores Table */}
        <div className="bg-white rounded-lg p-6 mb-6 print:border print:border-gray-300 print-avoid-break">
          <h3 className="text-lg font-bold text-gray-900 mb-4">Weekly Score Breakdown</h3>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-100 border-b">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-700 uppercase">Week</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Total Score</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Rating</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Work Hours</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Priority</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Completion</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Past Due</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {weeklyScores.map((ws, idx) => (
                  <tr key={idx} className="hover:bg-gray-50">
                    <td className="px-4 py-3 text-sm text-gray-900">
                      {formatDateInPacific(ws.record.startDate, { month: 'short', day: 'numeric' })} - {formatDateInPacific(ws.record.endDate, { month: 'short', day: 'numeric' })}
                    </td>
                    <td className={`px-4 py-3 text-center text-lg font-bold ${getPerformanceColor(ws.totalScore)}`}>
                      {ws.totalScore.toFixed(2)}
                    </td>
                    <td className="px-4 py-3 text-center text-sm font-semibold text-gray-700">
                      {ws.rating}
                    </td>
                    <td className="px-4 py-3 text-center text-sm text-gray-600">
                      {ws.breakdown.workHoursFulfillment.toFixed(1)}/25
                    </td>
                    <td className="px-4 py-3 text-center text-sm text-gray-600">
                      {ws.breakdown.taskPriorityHandling.toFixed(1)}/20
                    </td>
                    <td className="px-4 py-3 text-center text-sm text-gray-600">
                      {ws.breakdown.taskCompletionRate.toFixed(1)}/25
                    </td>
                    <td className="px-4 py-3 text-center text-sm text-gray-600">
                      {ws.breakdown.pastDueTaskManagement.toFixed(1)}/30
                    </td>
                  </tr>
                ))}
              </tbody>
              <tfoot className="bg-gray-50 border-t-2 border-gray-300">
                <tr>
                  <td className="px-4 py-3 text-sm font-bold text-gray-900">
                    Monthly Average
                  </td>
                  <td className={`px-4 py-3 text-center text-lg font-bold ${textColor}`}>
                    {monthlyAverage.toFixed(2)}
                  </td>
                  <td className="px-4 py-3 text-center text-sm font-bold text-gray-900">
                    {monthlyRating}
                  </td>
                  <td colSpan={4} className="px-4 py-3 text-center text-sm text-gray-600 italic">
                    Average of {weeklyScores.length} week(s)
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>

        {/* Rating Legend */}
        <div className="bg-white rounded-lg p-4 mb-6 border border-gray-200 print-avoid-break">
          <p className="text-xs font-semibold text-gray-600 mb-3">Rating Legend</p>
          <div className="grid grid-cols-2 gap-2 text-xs">
            <div>
              <span className="font-semibold text-green-600">90-100</span>
              <p className="text-gray-600">Excellent</p>
            </div>
            <div>
              <span className="font-semibold text-green-500">80-89</span>
              <p className="text-gray-600">Very Good</p>
            </div>
            <div>
              <span className="font-semibold text-blue-600">70-79</span>
              <p className="text-gray-600">Good</p>
            </div>
            <div>
              <span className="font-semibold text-red-600">Below 70</span>
              <p className="text-gray-600">Below Expectation</p>
            </div>
          </div>
        </div>

        {/* Monthly Summary Comment */}
        <div className="bg-blue-50 rounded-lg p-4 border border-blue-200 print-avoid-break">
          <div className="flex justify-between items-start mb-2">
            <p className="text-xs font-semibold text-blue-900">Monthly Performance Summary</p>
            {!monthlyComment && (
              <button
                onClick={generateMonthlyComment}
                disabled={isGenerating}
                className="text-xs text-blue-600 hover:text-blue-800 font-medium disabled:text-blue-300 print:hidden"
              >
                {isGenerating ? "Generating..." : "Generate Summary"}
              </button>
            )}
          </div>
          {isGenerating && (
            <p className="text-xs text-blue-700 mb-2">
              Generating AI summary...
            </p>
          )}
          {generateMessage && (
            <p className="text-xs text-blue-700 mb-2">
              {generateMessage}
            </p>
          )}
          <p className="text-sm text-gray-800 whitespace-pre-wrap">
            {monthlyComment || (
              <span className="italic text-gray-500">Click "Generate Summary" to create an AI-powered monthly performance summary</span>
            )}
          </p>
        </div>

        {monthlyAverage < 70 && (
          <div className="mt-4 bg-red-50 rounded-lg p-4 border border-red-200 print-avoid-break">
            <p className="text-sm font-bold text-red-600">
              ⚠️ WARNING: Monthly average is below 70%. If the monthly average remains below 70% for three consecutive months, it will trigger a formal warning review. Three confirmed warnings may result in reduction of hours or termination.
            </p>
          </div>
        )}
      </div>
    </>
  );
}
