"use client";

import { Employee } from "@/lib/employees";
import {
  calculateWeeklyPerformanceScore,
  getTaskPriorityHandlingBreakdown,
  getPerformanceRating,
  getPerformanceColor,
  getPerformanceBgColor,
} from "@/lib/performanceScoring";
import { formatDateInPacific } from "@/lib/dateUtils";
import { useEffect, useRef, useState } from "react";

interface MonthlyPerformanceReportProps {
  employee: Employee;
  year: number;
  month: number;
}

export default function MonthlyPerformanceReport({
  employee,
  year,
  month,
}: MonthlyPerformanceReportProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const [monthlyComment, setMonthlyComment] = useState<string>("");
  const [generateMessage, setGenerateMessage] = useState<string | null>(null);
  const [isEditing, setIsEditing] = useState(false);
  const [editedComment, setEditedComment] = useState<string>("");
  const [showEmailComposer, setShowEmailComposer] = useState(false);
  const [emailBody, setEmailBody] = useState("");
  const [emailAttachments, setEmailAttachments] = useState<File[]>([]);
  const [isSendingEmail, setIsSendingEmail] = useState(false);
  const [emailStatusMessage, setEmailStatusMessage] = useState<string | null>(null);
  const autoGeneratedRef = useRef(false);

  const monthNames = [
    "January",
    "February",
    "March",
    "April",
    "May",
    "June",
    "July",
    "August",
    "September",
    "October",
    "November",
    "December",
  ];

  const monthlyRecords = employee.weeklyRecords.filter((record) => {
    const startDate = new Date(`${record.startDate}T12:00:00`);
    return startDate.getFullYear() === year && startDate.getMonth() === month;
  });

  const weeklyScores = monthlyRecords.map((record) => {
    const score = calculateWeeklyPerformanceScore(record);
    const taskPriorityBreakdown = getTaskPriorityHandlingBreakdown(record);
    return {
      record,
      totalScore: score.totalScore,
      rating: getPerformanceRating(score.totalScore),
      breakdown: score,
      taskPriorityBreakdown,
    };
  });

  const monthlyAverage =
    weeklyScores.length > 0
      ? Math.round(
          (weeklyScores.reduce((sum, ws) => sum + ws.totalScore, 0) /
            weeklyScores.length) *
            100
        ) / 100
      : 0;

  const monthlyRating = getPerformanceRating(monthlyAverage);
  const textColor = getPerformanceColor(monthlyAverage);
  const bgColor = getPerformanceBgColor(monthlyAverage);

  const getTrend = () => {
    if (weeklyScores.length === 0) return "Insufficient data";

    const prevMonth = month === 0 ? 11 : month - 1;
    const prevYear = month === 0 ? year - 1 : year;

    const prevMonthRecords = employee.weeklyRecords.filter((record) => {
      const startDate = new Date(`${record.startDate}T12:00:00`);
      return startDate.getFullYear() === prevYear && startDate.getMonth() === prevMonth;
    });

    if (prevMonthRecords.length === 0) return "Insufficient data";

    const prevMonthScores = prevMonthRecords.map(
      (record) => calculateWeeklyPerformanceScore(record).totalScore
    );
    const prevMonthAverage =
      prevMonthScores.reduce((a, b) => a + b, 0) / prevMonthScores.length;

    const diff = monthlyAverage - prevMonthAverage;

    if (Math.abs(diff) < 3) return "Stable";
    if (diff > 0) return `Improving (+${diff.toFixed(1)})`;
    return `Declining (${diff.toFixed(1)})`;
  };

  const handlePrint = () => {
    const originalTitle = document.title;
    const yearMonth = `${year}${String(month + 1).padStart(2, "0")}`;
    document.title = `Monthly Performance Report_${employee.name}_${yearMonth}`;

    const restoreTitle = () => {
      document.title = originalTitle;
      window.removeEventListener("afterprint", restoreTitle);
    };

    window.addEventListener("afterprint", restoreTitle);
    window.print();

    setTimeout(() => {
      restoreTitle();
    }, 1500);
  };

  const monthLabel = `${monthNames[month]} ${year}`;
  const monthlySubject = `Monthly performance report ${monthLabel}`;
  const defaultMonthlyEmailBody = `Dear ${employee.name},

Please find attached your Monthly Performance Report for ${monthLabel}, which summarizes your weekly performance evaluations for this period.

As previously announced, monthly performance scores are calculated based on the average of weekly evaluation results in accordance with the Progressive Discipline & Performance Warning Policy.

Please review your report carefully, including overall performance trends and any areas identified for improvement.

If you have any questions regarding the evaluation results or performance expectations, please contact HR directly.

Thank you for your continued efforts.

Sincerely,
Human Resources
Whitewater University of California
3150 Almaden Expy, Suite 111
San Jose, CA 95118`;

  const handleSendEmail = async () => {
    if (!employee.email) {
      alert("Employee email is missing. Please update employee email first.");
      return;
    }

    setIsSendingEmail(true);
    setEmailStatusMessage(null);

    try {
      const formData = new FormData();
      formData.append("to", employee.email);
      formData.append("bcc", "chisu@wuc.edu, yannhuang@wuc.edu, yuguo@wuc.edu");
      formData.append("subject", monthlySubject);
      formData.append("body", emailBody);
      emailAttachments.forEach((file) => {
        formData.append("attachments", file);
      });

      const response = await fetch("/api/email/send", {
        method: "POST",
        body: formData,
      });

      const result = await response.json().catch(() => ({}));

      if (!response.ok) {
        throw new Error(result?.error || "Failed to send email");
      }

      setEmailStatusMessage("Email sent successfully.");
      setEmailAttachments([]);
    } catch (error) {
      setEmailStatusMessage(
        `Failed to send email: ${
          error instanceof Error ? error.message : String(error)
        }`
      );
    } finally {
      setIsSendingEmail(false);
    }
  };

  const saveMonthlyComment = async (comment: string, successMessage?: string) => {
    try {
      const response = await fetch("/api/monthly-comments", {
        method: "PUT",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          employeeId: employee.id,
          year,
          month,
          comment,
        }),
      });

      if (!response.ok) {
        setGenerateMessage("Failed to save monthly comment.");
        return false;
      }

      if (successMessage) {
        setGenerateMessage(successMessage);
      }
      return true;
    } catch (error) {
      console.error("Error saving monthly comment:", error);
      setGenerateMessage("Failed to save monthly comment.");
      return false;
    }
  };

  const generateMonthlyComment = async () => {
    if (weeklyScores.length === 0) {
      setGenerateMessage("No weekly records found for this month.");
      return;
    }

    setIsGenerating(true);
    setGenerateMessage(null);
    autoGeneratedRef.current = true;

    try {
      const response = await fetch("/api/ai/monthly-comment", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({
          employeeName: employee.name,
          employeeId: employee.id,
          year,
          month,
          monthName: monthNames[month],
          weeklyScores: weeklyScores.map((ws) => ({
            startDate: ws.record.startDate,
            endDate: ws.record.endDate,
            totalScore: ws.totalScore,
            rating: ws.rating,
            breakdown: ws.breakdown,
            taskPriorityBreakdown: ws.taskPriorityBreakdown,
          })),
          monthlyAverage,
          monthlyRating,
          workAuthorizationStatus: employee.workAuthorizationStatus,
        }),
      });

      if (!response.ok) {
        const errorText = await response.text();
        let errorPayload: any = null;
        try {
          errorPayload = JSON.parse(errorText);
        } catch {
          errorPayload = null;
        }

        if (
          errorPayload?.error === "GEMINI_QUOTA_EXCEEDED" ||
          errorPayload?.error === "GEMINI_SERVICE_UNAVAILABLE"
        ) {
          const fallback = buildFallbackComment();
          setMonthlyComment(fallback);
          setEditedComment(fallback);
          const message =
            errorPayload?.error === "GEMINI_QUOTA_EXCEEDED"
              ? "AI quota reached. A local fallback comment was generated and saved."
              : "AI service temporarily unavailable. A local fallback comment was generated and saved.";
          await saveMonthlyComment(fallback, message);
          setIsEditing(false);
          return;
        }

        setGenerateMessage("AI generation failed. Please try again later.");
        console.error("AI monthly comment generation failed:", errorText);
        return;
      }

      const data = await response.json();
      const generated = data?.comment?.trim();
      if (generated) {
        setMonthlyComment(generated);
        setEditedComment(generated);
        await saveMonthlyComment(generated, "AI comment generated and saved successfully.");
        setIsEditing(false);
      }
    } catch (error) {
      console.error("Error generating monthly comment:", error);
      setGenerateMessage("AI generation failed. Please try again later.");
    } finally {
      setIsGenerating(false);
    }
  };

  const handleEdit = () => {
    setEditedComment(monthlyComment);
    setIsEditing(true);
  };

  const handleSaveEdit = () => {
    const nextComment = editedComment.trim();
    setMonthlyComment(nextComment);
    setEditedComment(nextComment);
    setIsEditing(false);
    void saveMonthlyComment(nextComment, "Comment updated and saved.");
  };

  const handleCancelEdit = () => {
    setEditedComment(monthlyComment);
    setIsEditing(false);
  };

  const buildFallbackComment = () => {
    const trend = getTrend();
    const avgScore = monthlyAverage.toFixed(2);
    const weekCount = weeklyScores.length;

    if (monthlyAverage < 70) {
      return (
        `Your monthly average score for ${monthNames[month]} ${year} is ${avgScore}, which is below expectation. ` +
        `Based on ${weekCount} week(s) of data, your performance trend is ${trend}. ` +
        `This requires immediate improvement across all evaluation areas.\n\n` +
        `Critical areas needing attention: consistent work hour tracking, reducing overdue tasks, and improving task completion rates. ` +
        `Review each weekly evaluation to identify specific patterns and take corrective action immediately.`
      );
    }

    return (
      `Your monthly average score for ${monthNames[month]} ${year} is ${avgScore} (${monthlyRating}). ` +
      `Based on ${weekCount} week(s) of data, your performance trend shows ${trend}. ` +
      `Overall, you are meeting expectations with room for growth.\n\n` +
      `Continue your current performance level while focusing on areas flagged in individual weekly evaluations. ` +
      `Consistent execution and proactive task management will help maintain or improve your monthly average.`
    );
  };

  useEffect(() => {
    setMonthlyComment("");
    setEditedComment("");
    setGenerateMessage(null);
    setIsEditing(false);
    setIsGenerating(false);
  }, [employee.id, year, month]);

  useEffect(() => {
    setEmailBody(defaultMonthlyEmailBody);
  }, [defaultMonthlyEmailBody]);

  useEffect(() => {
    const loadSavedComment = async () => {
      try {
        const query = new URLSearchParams({
          employeeId: employee.id,
          year: String(year),
          month: String(month),
        }).toString();

        const response = await fetch(`/api/monthly-comments?${query}`);
        if (!response.ok) {
          return;
        }

        const data = await response.json();
        const savedComment = (data?.comment || "").trim();
        if (savedComment) {
          setMonthlyComment(savedComment);
          setEditedComment(savedComment);
        }
      } catch (error) {
        console.error("Error loading monthly comment:", error);
      }
    };

    void loadSavedComment();
  }, [employee.id, year, month]);

  if (monthlyRecords.length === 0) {
    return (
      <div className="bg-white rounded-lg shadow-md p-6">
        <h2 className="text-2xl font-bold text-gray-900 mb-4">
          Monthly Performance Report
        </h2>
        <p className="text-gray-600">
          No weekly records found for {monthNames[month]} {year}.
        </p>
      </div>
    );
  }

  return (
    <>
      <style jsx global>{`
        @media print {
          @page {
            size: A4;
            margin: 1.5cm;
          }

          * {
            -webkit-print-color-adjust: exact !important;
            print-color-adjust: exact !important;
            color-adjust: exact !important;
          }

          .print-avoid-break {
            page-break-inside: avoid !important;
            break-inside: avoid !important;
          }

          button {
            display: none !important;
          }

          header,
          footer {
            display: none !important;
          }

          body,
          html {
            background: white !important;
            margin: 0 !important;
            padding: 0 !important;
          }

          main {
            margin: 0 !important;
            padding: 0 !important;
          }

          .print\:hidden {
            display: none !important;
          }
        }
      `}</style>
      <div className={`rounded-lg shadow-md p-6 ${bgColor} print:shadow-none`}>
        <div className="mb-6 flex justify-between items-start">
          <div>
            <h2 className="text-2xl font-bold text-gray-900 mb-2">
              Monthly Performance Report
            </h2>
            <p className="text-sm text-gray-600">
              {employee.name} • {employee.id} • {monthNames[month]} {year}
            </p>
          </div>
          <div className="flex gap-2 print:hidden">
            <button
              onClick={() => setShowEmailComposer((prev) => !prev)}
              className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 transition-colors"
              type="button"
            >
              Email Report
            </button>
            <button
              onClick={handlePrint}
              className="px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 transition-colors flex items-center gap-2"
              type="button"
            >
              <svg
                xmlns="http://www.w3.org/2000/svg"
                className="h-5 w-5"
                fill="none"
                viewBox="0 0 24 24"
                stroke="currentColor"
              >
                <path
                  strokeLinecap="round"
                  strokeLinejoin="round"
                  strokeWidth={2}
                  d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H9a2 2 0 00-2 2v4h10z"
                />
              </svg>
              Print PDF
            </button>
          </div>
        </div>

        {showEmailComposer && (
          <div className="bg-white rounded-lg p-4 mb-6 border border-green-200 print:hidden">
            <p className="text-sm font-semibold text-gray-900 mb-2">
              To: {employee.email || "(No employee email)"}
            </p>
            <p className="text-sm text-gray-600 mb-2">
              BCC: chisu@wuc.edu, yannhuang@wuc.edu, yuguo@wuc.edu
            </p>
            <p className="text-sm font-semibold text-gray-900 mb-2">
              Subject: {monthlySubject}
            </p>
            <textarea
              value={emailBody}
              onChange={(e) => setEmailBody(e.target.value)}
              placeholder="Enter email content here..."
              className="w-full min-h-32 px-3 py-2 border border-gray-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-green-500"
            />
            <div className="mt-3">
              <label className="block text-sm font-semibold text-gray-900 mb-2">
                Attach files
              </label>
              <label className="inline-flex items-center gap-2 px-4 py-2 bg-blue-600 text-white rounded-lg hover:bg-blue-700 cursor-pointer transition-colors">
                <svg
                  className="w-5 h-5"
                  fill="none"
                  stroke="currentColor"
                  viewBox="0 0 24 24"
                >
                  <path
                    strokeLinecap="round"
                    strokeLinejoin="round"
                    strokeWidth={2}
                    d="M15.172 7l-6.586 6.586a2 2 0 102.828 2.828l6.414-6.586a4 4 0 00-5.656-5.656l-6.415 6.585a6 6 0 108.486 8.486L20.5 13"
                  />
                </svg>
                Choose Files
                <input
                  type="file"
                  multiple
                  onChange={(e) => {
                    const files = Array.from(e.target.files || []);
                    setEmailAttachments(files);
                  }}
                  className="hidden"
                />
              </label>
              {emailAttachments.length > 0 && (
                <p className="text-xs text-gray-600 mt-2">
                  Selected: {emailAttachments.map((f) => f.name).join(", ")}
                </p>
              )}
            </div>
            {emailStatusMessage && (
              <p className="text-sm text-gray-700 mt-3">{emailStatusMessage}</p>
            )}
            <div className="mt-3 flex justify-end gap-2">
              <button
                onClick={() => setShowEmailComposer(false)}
                className="px-4 py-2 bg-gray-200 text-gray-800 rounded-lg hover:bg-gray-300"
                type="button"
              >
                Cancel
              </button>
              <button
                onClick={handleSendEmail}
                disabled={isSendingEmail}
                className="px-4 py-2 bg-green-600 text-white rounded-lg hover:bg-green-700 disabled:bg-green-300"
                type="button"
              >
                {isSendingEmail ? "Sending..." : "Send Email"}
              </button>
            </div>
          </div>
        )}

        <div className="bg-white rounded-lg p-6 mb-6 border-l-4 border-l-blue-500 print:border print:border-gray-300 print-avoid-break">
          <div className="grid grid-cols-1 md:grid-cols-3 gap-6">
            <div>
              <p className="text-sm font-semibold text-gray-600 uppercase mb-2">
                Monthly Average
              </p>
              <p className={`text-4xl font-bold ${textColor}`}>
                {monthlyAverage.toFixed(2)}
              </p>
              <p className={`text-sm font-semibold mt-1 ${textColor}`}>
                {monthlyRating}
              </p>
            </div>
            <div>
              <p className="text-sm font-semibold text-gray-600 uppercase mb-2">
                Weeks Evaluated
              </p>
              <p className="text-4xl font-bold text-gray-900">
                {weeklyScores.length}
              </p>
            </div>
            <div>
              <p className="text-sm font-semibold text-gray-600 uppercase mb-2">
                Performance Trend
              </p>
              <p className="text-2xl font-bold text-gray-900">{getTrend()}</p>
            </div>
          </div>
        </div>

        <div className="bg-white rounded-lg p-6 mb-6 print:border print:border-gray-300 print-avoid-break">
          <h3 className="text-lg font-bold text-gray-900 mb-4">Weekly Score Breakdown</h3>
          <p className="text-xs text-gray-500 mb-3">
            Task Priority Handling direct deductions apply to urgent overdue tasks, high overdue tasks, and assigned tasks left with no priority. A no-priority task still deducts points even if it was completed.
          </p>
          <div className="overflow-x-auto">
            <table className="w-full">
              <thead className="bg-gray-100 border-b">
                <tr>
                  <th className="px-4 py-3 text-left text-xs font-semibold text-gray-700 uppercase">Week</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Total Score</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Rating</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Work Hours</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Priority</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Completion</th>
                  <th className="px-4 py-3 text-center text-xs font-semibold text-gray-700 uppercase">Past Due</th>
                </tr>
              </thead>
              <tbody className="divide-y divide-gray-200">
                {weeklyScores.map((ws, idx) => (
                  <tr key={idx} className="hover:bg-gray-50">
                    <td className="px-4 py-3 text-sm text-gray-900">
                      {formatDateInPacific(ws.record.startDate, {
                        month: "short",
                        day: "numeric",
                      })}{" "}
                      -{" "}
                      {formatDateInPacific(ws.record.endDate, {
                        month: "short",
                        day: "numeric",
                      })}
                    </td>
                    <td
                      className={`px-4 py-3 text-center text-lg font-bold ${getPerformanceColor(
                        ws.totalScore
                      )}`}
                    >
                      {ws.totalScore.toFixed(2)}
                    </td>
                    <td className="px-4 py-3 text-center text-sm font-semibold text-gray-700">
                      {ws.rating}
                    </td>
                    <td className="px-4 py-3 text-center text-sm text-gray-600">
                      {ws.breakdown.workHoursFulfillment.toFixed(1)}/25
                    </td>
                    <td className="px-4 py-3 text-center text-sm text-gray-600">
                      {ws.breakdown.taskPriorityHandling.toFixed(1)}/20
                    </td>
                    <td className="px-4 py-3 text-center text-sm text-gray-600">
                      {ws.breakdown.taskCompletionRate.toFixed(1)}/25
                    </td>
                    <td className="px-4 py-3 text-center text-sm text-gray-600">
                      {ws.breakdown.pastDueTaskManagement.toFixed(1)}/30
                    </td>
                  </tr>
                ))}
              </tbody>
              <tfoot className="bg-gray-50 border-t-2 border-gray-300">
                <tr>
                  <td className="px-4 py-3 text-sm font-bold text-gray-900">Monthly Average</td>
                  <td className={`px-4 py-3 text-center text-lg font-bold ${textColor}`}>
                    {monthlyAverage.toFixed(2)}
                  </td>
                  <td className="px-4 py-3 text-center text-sm font-bold text-gray-900">
                    {monthlyRating}
                  </td>
                  <td colSpan={4} className="px-4 py-3 text-center text-sm text-gray-600 italic">
                    Average of {weeklyScores.length} week(s)
                  </td>
                </tr>
              </tfoot>
            </table>
          </div>
        </div>

        <div className="bg-white rounded-lg p-4 mb-6 border border-gray-200 print-avoid-break">
          <p className="text-xs font-semibold text-gray-600 mb-3">Rating Legend</p>
          <div className="grid grid-cols-2 gap-2 text-xs">
            <div>
              <span className="font-semibold text-green-600">90-100</span>
              <p className="text-gray-600">Excellent</p>
            </div>
            <div>
              <span className="font-semibold text-green-500">80-89</span>
              <p className="text-gray-600">Very Good</p>
            </div>
            <div>
              <span className="font-semibold text-blue-600">70-79</span>
              <p className="text-gray-600">Good</p>
            </div>
            <div>
              <span className="font-semibold text-red-600">Below 70</span>
              <p className="text-gray-600">Below Expectation</p>
            </div>
          </div>
        </div>

        <div className="bg-blue-50 rounded-lg p-4 border border-blue-200 print-avoid-break">
          <div className="flex justify-between items-start mb-2">
            <p className="text-xs font-semibold text-blue-900">Monthly Performance Summary</p>
            <div className="flex gap-2 print:hidden">
              {!monthlyComment && (
                <button
                  onClick={generateMonthlyComment}
                  disabled={isGenerating}
                  className="text-xs text-blue-600 hover:text-blue-800 font-medium disabled:text-blue-300"
                >
                  {isGenerating ? "Generating..." : "Generate Summary"}
                </button>
              )}
              {monthlyComment && !isEditing && (
                <>
                  <button
                    onClick={generateMonthlyComment}
                    disabled={isGenerating}
                    className="text-xs text-blue-600 hover:text-blue-800 font-medium disabled:text-blue-300"
                  >
                    {isGenerating ? "Regenerating..." : "Regenerate"}
                  </button>
                  <button
                    onClick={handleEdit}
                    className="text-xs text-green-600 hover:text-green-800 font-medium"
                  >
                    Edit
                  </button>
                </>
              )}
              {isEditing && (
                <>
                  <button
                    onClick={handleSaveEdit}
                    className="text-xs text-green-600 hover:text-green-800 font-medium"
                  >
                    Save
                  </button>
                  <button
                    onClick={handleCancelEdit}
                    className="text-xs text-gray-600 hover:text-gray-800 font-medium"
                  >
                    Cancel
                  </button>
                </>
              )}
            </div>
          </div>
          {isGenerating && (
            <p className="text-xs text-blue-700 mb-2">Generating AI summary...</p>
          )}
          {generateMessage && (
            <p className="text-xs text-blue-700 mb-2">{generateMessage}</p>
          )}
          {isEditing ? (
            <textarea
              value={editedComment}
              onChange={(e) => setEditedComment(e.target.value)}
              className="w-full min-h-40 text-sm text-gray-800 p-2 border border-blue-300 rounded-lg focus:outline-none focus:ring-2 focus:ring-blue-400 print:hidden"
              placeholder="Enter manager's comments..."
            />
          ) : (
            <p className="text-sm text-gray-800 whitespace-pre-wrap">
              {monthlyComment || (
                <span className="italic text-gray-500">
                  Click "Generate Summary" to create an AI-powered monthly performance summary
                </span>
              )}
            </p>
          )}
        </div>

        {monthlyAverage < 70 && (
          <div className="mt-4 bg-red-50 rounded-lg p-4 border border-red-200 print-avoid-break">
            <p className="text-sm font-bold text-red-600">
              ⚠️ Performance Review Notice: A monthly performance average below 70% triggers a formal warning review under the Progressive Discipline & Performance Warning Policy. Accumulation of three confirmed warnings may lead to further disciplinary action, including reduction of work hours or termination of employment.
            </p>
          </div>
        )}
      </div>
    </>
  );
}
