export type IncidentTotals = {
  confirmedMistakes: number;
  confirmedWarnings: number;
  requiresDisciplinaryAction: boolean;
};

export async function calculateIncidentTotals(
  prisma: any,
  employeeDbIds?: string[]
): Promise<Map<string, IncidentTotals>> {
  const where = {
    status: "CONFIRMED",
    ...(employeeDbIds && employeeDbIds.length > 0
      ? { employeeId: { in: employeeDbIds } }
      : {}),
  };

  const [mistakeCounts, warningCounts] = await Promise.all([
    prisma.incidentRecord.groupBy({
      by: ["employeeId"],
      where: { ...where, recordType: "MISTAKE" },
      _count: { _all: true },
    }),
    prisma.incidentRecord.groupBy({
      by: ["employeeId"],
      where: {
        ...where,
        recordType: "WARNING",
        // A warning is only considered confirmed for totals when appeal is declined.
        appealDecision: "DECLINED",
      },
      _count: { _all: true },
    }),
  ]);

  const totalsMap = new Map<string, IncidentTotals>();

  for (const entry of mistakeCounts) {
    totalsMap.set(entry.employeeId, {
      confirmedMistakes: entry._count._all,
      confirmedWarnings: 0,
      requiresDisciplinaryAction: false,
    });
  }

  for (const entry of warningCounts) {
    const existing = totalsMap.get(entry.employeeId);
    const confirmedWarnings = entry._count._all;
    const confirmedMistakes = existing?.confirmedMistakes ?? 0;

    totalsMap.set(entry.employeeId, {
      confirmedMistakes,
      confirmedWarnings,
      requiresDisciplinaryAction: confirmedWarnings >= 3,
    });
  }

  for (const [employeeId, totals] of totalsMap) {
    if (totals.confirmedWarnings < 3) {
      totalsMap.set(employeeId, {
        ...totals,
        requiresDisciplinaryAction: false,
      });
    }
  }

  return totalsMap;
}

export async function syncAutomaticWarningsForEmployee(
  tx: any,
  employeeDbId: string,
  createdBy: string
): Promise<void> {
  const [confirmedMistakes, autoGeneratedWarnings, employeeSnapshot] = await Promise.all([
    tx.incidentRecord.count({
      where: {
        employeeId: employeeDbId,
        recordType: "MISTAKE",
        status: "CONFIRMED",
      },
    }),
    tx.incidentRecord.count({
      where: {
        employeeId: employeeDbId,
        recordType: "WARNING",
        status: "CONFIRMED",
        isAutoGenerated: true,
      },
    }),
    tx.employee.findUnique({
      where: { id: employeeDbId },
      select: { name: true, department: true },
    }),
  ]);

  if (!employeeSnapshot) {
    return;
  }

  const expectedAutoWarnings = Math.floor(confirmedMistakes / 5);
  const missingAutoWarnings = expectedAutoWarnings - autoGeneratedWarnings;

  if (missingAutoWarnings <= 0) {
    return;
  }

  for (let index = 0; index < missingAutoWarnings; index += 1) {
    const thresholdNumber = (autoGeneratedWarnings + index + 1) * 5;
    const generatedWarning = await tx.incidentRecord.create({
      data: {
        employeeId: employeeDbId,
        name: employeeSnapshot.name,
        department: employeeSnapshot.department,
        manager: "AUTO-GENERATED",
        recordType: "WARNING",
        occurrenceDate: new Date(),
        issuedBy: "SYSTEM",
        reason: `Auto-generated warning triggered after confirmed mistake threshold was reached.`,
        status: "CONFIRMED",
        appealDecision: "PENDING",
        finalAction: "NONE",
        isAutoGenerated: true,
      },
    });

    await tx.incidentHistory.create({
      data: {
        incidentId: generatedWarning.id,
        type: "SYSTEM",
        createdBy,
        memo: `System auto-generated warning because confirmed mistakes reached ${thresholdNumber}.`,
      },
    });
  }
}

export function formatIncidentRecord(
  record: any,
  totalsMap: Map<string, IncidentTotals>
) {
  const totals =
    totalsMap.get(record.employeeId) ??
    ({
      confirmedMistakes: 0,
      confirmedWarnings: 0,
      requiresDisciplinaryAction: false,
    } satisfies IncidentTotals);

  return {
    id: record.id,
    employeeDbId: record.employeeId,
    employeeId: record.employee.employeeId,
    name: record.name,
    department: record.department,
    manager: record.manager,
    recordType: record.recordType,
    occurrenceDate: record.occurrenceDate.toISOString().split("T")[0],
    issuedBy: record.issuedBy,
    reason: record.reason ?? "",
    status: record.status,
    appealDecision: record.appealDecision,
    decisionDate: record.decisionDate ? record.decisionDate.toISOString().split("T")[0] : "",
    reviewedBy: record.reviewedBy ?? "",
    finalAction: record.finalAction,
    isAutoGenerated: record.isAutoGenerated,
    meetingCompleted: record.meetingCompleted ?? false,
    emailSent: record.emailSent ?? false,
    followUpEmailSent: record.followUpEmailSent ?? false,
    improvementPlanReceived: record.improvementPlanReceived ?? false,
    pipAdjustmentAgreementSent: record.pipAdjustmentAgreementSent ?? false,
    totals,
    histories: record.histories.map((history: any) => ({
      id: history.id,
      memo: history.memo,
      type: history.type,
      createdAt: history.createdAt.toISOString(),
      createdBy: history.createdBy,
    })),
  };
}
